from .TeacherStatisticsDB import TeacherStatistics, TeacherStatisticsDB
from .TestQuestionsDB import TestQuestions, TestQuestionsDB
from .TestsDB import Tests, TestsDB
from .UsersDB import Users, UsersDB
from .UsersStatisticsDB import UsersStatistics, UsersStatisticsDB
from .AlgebraDB import Algebra, AlgebraDB
from .BiologyDB import Biology, BiologyDB
from .ChemistryDB import Chemistry, ChemistryDB
from .EnglishDB import English, EnglishDB
from .GeographyDB import Geography, GeographyDB
from .GeometryDB import Geometry, GeometryDB
from .HistoryDB import History, HistoryDB
from .InformaticsDB import Informatics, InformaticsDB
from .LiteratureDB import Literature, LiteratureDB
from .MathematicsBaseDB import MathematicsBase, MathematicsBaseDB
from .MathematicsDB import Mathematics, MathematicsDB
from .MathematicsDepthDB import MathematicsDepth, MathematicsDepthDB
from .MathematicsProfileDB import MathematicsProfile, MathematicsProfileDB
from .OutwardThingsDB import OutwardThings, OutwardThingsDB
from .PhysicsDB import Physics, PhysicsDB
from .ProbabilityTheoryDB import ProbabilityTheory, ProbabilityTheoryDB
from .ReadingComprehensionDB import ReadingComprehension, ReadingComprehensionDB
from .RussianDB import Russian, RussianDB
from .SocialScienceDB import SocialScience, SocialScienceDB